# Generated by Django 4.2.14 on 2024-11-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='files',
            name='db_main_fil_file_co_ba1d4e_idx',
        ),
    ]
