# Generated by Django 4.2.14 on 2024-11-13 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_main', '0002_alter_files_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_main.projects', verbose_name='Kategoriya'),
        ),
    ]
