# Generated by Django 4.2.14 on 2024-07-30 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_main', '0002_files_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddField(
            model_name='projects',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Pastgi Kategoriya'),
        ),
    ]
