# Generated by Django 4.2.14 on 2024-08-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_main', '0003_files_user_projects_user_alter_subcategories_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='files',
        ),
        migrations.AddField(
            model_name='files',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='db_main.projects', verbose_name='Kategoriya'),
        ),
    ]
