# Generated by Django 4.2.14 on 2024-11-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_main', '0003_alter_files_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file_code',
            field=models.CharField(blank=True, db_index=True, max_length=25, null=True, verbose_name='Fayil Kodi'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='subject',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Izoh'),
        ),
        migrations.AddIndex(
            model_name='categories',
            index=models.Index(fields=['name'], name='db_main_cat_name_2f4de8_idx'),
        ),
        migrations.AddIndex(
            model_name='files',
            index=models.Index(fields=['file_code'], name='db_main_fil_file_co_ba1d4e_idx'),
        ),
        migrations.AddIndex(
            model_name='projects',
            index=models.Index(fields=['name', 'subcategories'], name='db_main_pro_name_ec6753_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategories',
            index=models.Index(fields=['categories', 'name'], name='db_main_sub_categor_90a78d_idx'),
        ),
    ]
